### ISSUE TITLE
Running environment

### ISSUE THREAD

**Issue by felicitywang** [LHolten/DialoGTP-MMI-decoder#1]
Hi,
Thank you very much for this great work. Could you share your running environment(python version / pip list)? With Python3.7 and PyTorch 1.3.1 for Cuda 10.1 I got the runtime error
```
usr >> hello
Traceback (most recent call last):
  File "interact.py", line 116, in <module>
    my_response = generate_message(my_message_list)
  File "interact.py", line 98, in generate_message
    result = _get_response(total_input[:, -1:], past)
  File "interact.py", line 47, in _get_response
    output_token = torch.multinomial(F.softmax(output_token, dim=-1), num_samples=1)
RuntimeError: "multinomial_kernel_cuda" not implemented for 'Half'
```

I imagine this wouldn't happen if I use the same environment. 
Thank you.

**Comment by LHolten** [comment]
I just checked and these are the python / pytorch / cuda versions
```
python -V
Python 3.7.4
-----
conda list
pytorch                   1.2.0           py3.7_cuda100_cudnn7_1    pytorch
cudatoolkit               10.0.130                      0
```
I will update my pytorch version and see if I can solve the problem

**Comment by LHolten** [comment]
For now if you have enough GPU memory you can remove these 4 lines.
https://github.com/LHolten/DialoGTP-MMI-decoder/blob/d3bf76a0de950a3437583b97c2b87a9b4f2e6fcc/interact.py#L18-L19
https://github.com/LHolten/DialoGTP-MMI-decoder/blob/d3bf76a0de950a3437583b97c2b87a9b4f2e6fcc/interact.py#L30-L31
Or you can use CPU by setting this to `'cpu'`
https://github.com/LHolten/DialoGTP-MMI-decoder/blob/d3bf76a0de950a3437583b97c2b87a9b4f2e6fcc/config.py#L8
Or you can downgrade to pytorch 1.2.0

**Comment by LHolten** [comment]
Should work with pytorch 1.3 now
